insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (200, '1.0.0.00.00.00.00',0, null, 'ATIVO', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (201, '1.1.0.00.00.00.00',0, null, 'CIRCULANTE', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (202, '1.1.1.00.00.00.00',0, null, 'Disponível', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (203, '1.1.1.00.00.00.00',0,1, 'Caixa ', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (204, '1.1.1.00.00.00.00',0,2, 'Bancos Conta Movimento', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (205, '1.1.2.00.00.00.00',0, null, 'Realizações', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (206, '1.1.2.00.00.00.00',0,1, 'Clientes', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (207, '1.1.2.00.00.00.00',0,2, '(-) Duplicatas Descontadas', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (208, '1.1.2.00.00.00.00',0,3, 'Aplicações Financeiras', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (209, '1.1.2.00.00.00.00',0,4, 'Impostos a Recuperar ', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (210, '1.1.2.00.00.00.00',0,5, 'Despesas do Exercício Seguinte', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (211, '1.1.2.00.00.00.00',0,6, '(-) Provisão para Devedores Duvidosos', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (212, '1.1.3.00.00.00.00',0, null, 'Estoques', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (213, '1.1.3.00.00.00.00',0,1, 'Estoque de Mercadorias', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (214, '1.1.3.00.00.00.00',0,2, '(-) Provisão para Ajuste ao Valor de Mercado', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (215, '1.2.0.00.00.00.00',0, null, 'ATIVO REALIZÁVEL A LONGO PRAZO', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (216, '1.2.1.00.00.00.00',0, null, 'Realizações', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (217, '1.2.1.00.00.00.00',0,1, 'Títulos a Receber', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (218, '1.3.0.00.00.00.00',0, null, 'ATIVO PERMANENTE', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (219, '1.3.1.00.00.00.00',0, null, 'Investimentos', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (220, '1.3.1.00.00.00.00',0,1, 'Participações em Outras Cias', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (221, '1.3.1.00.00.00.00',0,2, 'Imóveis para Renda', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (222, '1.3.2.00.00.00.00',0, null, 'Imobilizado', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (223, '1.3.2.00.00.00.00',0,1, 'Equipamentos de Informática', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (224, '1.3.2.00.00.00.00',0,2, 'Imóveis ', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (225, '1.3.2.00.00.00.00',0,3, 'Instalações', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (226, '1.3.2.00.00.00.00',0,4, 'Máquinas e Equipamentos', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (227, '1.3.2.00.00.00.00',0,5, 'Móveis e Utensílios', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (228, '1.3.2.00.00.00.00',0,6, 'Veículos', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (229, '1.3.2.00.00.00.00',0,7, '(-) Depreciação Acumulada', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (230, '1.3.3.00.00.00.00',0, null, 'Diferido', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (231, '1.3.3.00.00.00.00',0,1, 'Despesas Pré-Operacionais', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (232, '1.3.3.00.00.00.00',0,2, 'Despesas com Desenvolvimento de Sistemas', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (233, '1.2.2.00.00.00.00',0,3, 'Despesas com Desenvolvimento de Novos Produtos ', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (234, '1.3.3.00.00.00.00',0,4, '(-) Amortização Acumulada', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (235, '2.0.0.00.00.00.00',0, null, 'PASSIVO', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (236, '2.1.0.00.00.00.00',0, null, 'CIRCULANTE', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (237, '2.1.1.00.00.00.00',0, null, 'Obrigações', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (238, '2.1.1.00.00.00.00',0,1, 'Fornecedores', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (239, '2.1.1.00.00.00.00',0,2, 'Aluguéis a Pagar', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (240, '2.1.1.00.00.00.00',0,3, 'Empréstimos a Pagar', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (241, '2.1.1.00.00.00.00',0,4, 'ICMS a Recolher', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (242, '2.1.1.00.00.00.00',0,5, 'Imposto de Renda a Pagar', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (243, '2.1.1.00.00.00.00',0,6, 'IR Fonte a Recolher', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (244, '2.1.1.00.00.00.00',0,7, 'Contribuições Previdenciárias  a Recolher ', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (245, '2.1.1.00.00.00.00',0,8, 'FGTS a Recolher', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (246, '2.1.1.00.00.00.00',0,9, 'Honorários da Diretoria a Pagar', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (247, '2.1.1.00.00.00.00',0,10, 'Salários a Pagar', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (248, '2.1.1.00.00.00.00',0,11, 'Dividendos a pagar', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (249, '2.1.1.00.00.00.00',0,12, 'Outras Obrigações a Pagar', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (250, '2.2.0.00.00.00.00',0, null, 'EXIGÍVEL A LONGO PRAZO', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (251, '2.2.1.00.00.00.00',0, null, 'Obrigações', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (252, '2.2.1.00.00.00.00',0,1, 'Financiamentos a Pagar', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (253, '2.3.0.00.00.00.00',0, null, 'RESULTADO DE EXERCÍCIOS FUTUROS', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (254, '2.3.1.00.00.00.00',0, null, 'Resultados Futuros', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (255, '2.3.1.00.00.00.00',0,1, 'Receitas de Exercícios Futuros ', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (256, '2.3.1.00.00.00.00',0,2, '(-) Custos e Despesas', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (257, '2.4.0.00.00.00.00',0, null, 'PATRIMÔNIO LÍQUIDO', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (258, '2.4.1.00.00.00.00',0, null, 'Capital', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (259, '2.4.1.00.00.00.00',0,1, 'Capital', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (260, '2.4.1.00.00.00.00',0,2, '(-) Capital a Realizar', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (261, '2.4.2.00.00.00.00',0, null, 'Reservas de Capital', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (262, '2.4.2.00.00.00.00',0,1, 'Ágio na Emissão de Ações', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (263, '2.4.3.00.00.00.00',0, null, 'Reservas de Reavaliação', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (264, '2.4.3.00.00.00.00',0,1, 'Reavaliação do Permanente', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (265, '2.4.4.00.00.00.00',0, null, 'Reservas de Lucros', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (266, '2.4.4.00.00.00.00',0,1, 'Reserva Legal', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (267, '2.4.5.00.00.00.00',0, null, 'Lucros ou Prejuízos Acumulados', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (268, '2.4.5.00.00.00.00',0,1, 'Lucros Acumulados', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (269, '2.4.5.00.00.00.00',0,2, '(-) Prejuízos Acumulados', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (270, '3.0.0.00.00.00.00',0, null, 'DESPESAS  ', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (271, '3.3.0.00.00.00.00',0, null, 'DESPESAS OPERACIONAIS', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (272, '3.3.1.00.00.00.00',0, null, 'Despesas com Vendas', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (273, '3.3.1.00.00.00.00',0,1, 'Comissões sobre Vendas', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (274, '3.3.1.00.00.00.00',0,2, 'Fretes e Carretos', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (275, '3.3.1.00.00.00.00',0,3, 'Material de Embalagem', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (276, '3.3.1.00.00.00.00',0,4, 'Propaganda e Publicidade', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (277, '3.3.1.00.00.00.00',0,5, 'Despesas c/ Devedores  Duvidosos', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (278, '3.3.2.00.00.00.00',0, null, 'Despesas Administrativas', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (279, '3.3.2.00.00.00.00',0,1, 'Aluguel ', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (280, '3.3.2.00.00.00.00',0,2, 'Energia Elétrica', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (281, '3.3.2.00.00.00.00',0,3, 'Água ', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (282, '3.3.2.00.00.00.00',0,4, 'Correios ', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (283, '3.3.2.00.00.00.00',0,5, 'Depreciações', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (284, '3.3.2.00.00.00.00',0,6, 'Amortizações', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (285, '3.3.2.00.00.00.00',0,7, 'Fretes e Carretos', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (286, '3.3.2.00.00.00.00',0,8, 'Material de Expediente', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (287, '3.3.2.00.00.00.00',0,9, 'Prêmios de Seguro', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (288, '3.3.2.00.00.00.00',0,10, 'Comunicações', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (289, '3.3.2.00.00.00.00',0,11, 'Impostos e Taxas', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (290, '3.3.2.00.00.00.00',0,12, 'Serviços de Terceiros', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (291, '3.3.2.00.00.00.00',0,13, 'Multas Fiscais', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (292, '3.3.2.00.00.00.00',0,14, 'Salários', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (293, '3.3.2.00.00.00.00',0,15, 'Honorários da Diretoria', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (294, '3.3.2.00.00.00.00',0,16, 'Décimo Terceiro Salário', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (295, '3.3.2.00.00.00.00',0,17, 'Encargos Sociais', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (296, '3.3.2.00.00.00.00',0,18, 'Férias ', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (297, '3.3.3.00.00.00.00',0, null, 'Despesas Financeiras', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (298, '3.3.3.00.00.00.00',0,1, 'Despesas Bancárias', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (299, '3.3.3.00.00.00.00',0,2, 'Juros Passivos', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (300, '3.3.3.00.00.00.00',0,3, 'Descontos Concedidos', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (301, '3.3.4.00.00.00.00',0, null, 'Outras Despesas Operacionais', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (302, '3.3.4.00.00.00.00',0,1, 'Prejuízo de Participação em outras Cias ', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (303, '3.3.4.00.00.00.00',0,2, 'Despesas Eventuais', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (304, '3.4.0.00.00.00.00',0, null, 'DESPESAS NÃO OPERACIONAIS', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (305, '3.4.1.00.00.00.00',0, null, 'Perdas  não Operacionais', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (306, '3.4.1.00.00.00.00',0,1, 'Perdas na Alienação de Bens', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (307, '4.0.0.00.00.00.00',0, null, 'RECEITAS ', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (308, '4.1.0.00.00.00.00',0, null, 'RECEITAS OPERACIONAIS', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (309, '4.1.1.00.00.00.00',0, null, 'Receitas de Vendas ', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (310, '4.1.1.00.00.00.00',0,1, 'Venda de Mercadorias', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (311, '4.1.1.00.00.00.00',0,2, '(-) Vendas Anuladas', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (312, '4.1.1.00.00.00.00',0,3, '(-) ICMS sobre Vendas', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (313, '4.1.1.00.00.00.00',0,4, '(-) PIS sobre Faturamento', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (314, '4.1.2.00.00.00.00',0, null, 'Receitas de Serviços prestados', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (315, '4.1.2.00.00.00.00',0,1, 'Venda de Serviços', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (316, '4.1.2.00.00.00.00',0,2, '(-) ISSQN sobre Faturamento', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (317, '4.1.3.00.00.00.00',0, null, 'Receitas Financeiras', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (318, '4.1.3.00.00.00.00',0,1, 'Rendimentos de Aplicações Financeiras', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (319, '4.1.3.00.00.00.00',0,2, 'Descontos Obtidos', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (320, '4.1.3.00.00.00.00',0,3, 'Juros Ativos', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (321, '4.1.4.00.00.00.00',0, null, 'Outras Receitas Operacionais', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (322, '4.1.4.00.00.00.00',0,1, 'Lucros de Participações em Outras Cias', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (323, '4.1.4.00.00.00.00',0,2, 'Reversão de Provisão Para Devedores Duvidosos ', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (324, '4.1.4.00.00.00.00',0,3, 'Receitas Eventuais', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (325, '4.2.0.00.00.00.00',0, null, 'RECEITAS NÃO OPERACIONAIS', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (326, '4.2.1.00.00.00.00',0, null, 'Ganhos não Operacionais', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (327, '4.2.1.00.00.00.00',0,1, 'Ganho na Alienação de Bens', 'CREDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (328, '5.0.0.00.00.00.00',0, null, 'CONTAS DE APURAÇÃO DE RESULTADOS', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (329, '5.1.0.00.00.00.00',0, null, 'APURAÇÃO DE RESULTADO', 'CREDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (330, '5.1.1.00.00.00.00',0, null, 'Apuração de Resultado', 'DEVEDORA', 'SINTETICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (331, '5.1.1.00.00.00.00',0,1, 'Custo das Mercadorias Vendidas (CMV)', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (332, '5.1.1.00.00.00.00',0,2, 'Resultado com Vendas de Mercadorias (RVM)', 'DEVEDORA', 'ANALITICA',1);
insert into contas (id_conta, estrutura, nivel,ordem, nome, conta_origem, conta_tipo, id_plano_contas) values (333, '5.1.1.00.00.00.00',0,3, 'Apuração do Resultado do Exercício (ARE)', 'DEVEDORA', 'ANALITICA',1);