INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (200, '1.0.0.00.00.00.00', 0, 'ATIVO', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (201, '1.1.0.00.00.00.00', 0, 'CIRCULANTE', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (202, '1.1.1.00.00.00.00', 0, 'Disponível', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (203, '1.1.1.01.00.00.00', 0, 'Caixa ', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (204, '1.1.1.02.00.00.00', 0, 'Bancos Conta Movimento', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (205, '1.1.2.00.00.00.00', 0, 'Realizações', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (206, '1.1.2.01.00.00.00', 0, 'Clientes', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (207, '1.1.2.02.00.00.00', 0, '(-) Duplicatas Descontadas', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (208, '1.1.2.03.00.00.00', 0, 'Aplicações Financeiras', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (209, '1.1.2.04.00.00.00', 0, 'Impostos a Recuperar ', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (210, '1.1.2.05.00.00.00', 0, 'Despesas do Exercício Seguinte', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (211, '1.1.2.06.00.00.00', 0, '(-) Provisão para Devedores Duvidosos', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (212, '1.1.3.00.00.00.00', 0, 'Estoques', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (213, '1.1.3.01.00.00.00', 0, 'Estoque de Mercadorias', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (214, '1.1.3.02.00.00.00', 0, '(-) Provisão para Ajuste ao Valor de Mercado', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (215, '1.2.0.00.00.00.00', 0, 'ATIVO REALIZÁVEL A LONGO PRAZO', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (216, '1.2.1.00.00.00.00', 0, 'Realizações', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (217, '1.2.1.01.00.00.00', 0, 'Títulos a Receber', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (218, '1.3.0.00.00.00.00', 0, 'ATIVO PERMANENTE', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (219, '1.3.1.00.00.00.00', 0, 'Investimentos', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (220, '1.3.1.01.00.00.00', 0, 'Participações em Outras Cias', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (221, '1.3.1.02.00.00.00', 0, 'Imóveis para Renda', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (222, '1.3.2.00.00.00.00', 0, 'Imobilizado', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (223, '1.3.2.01.00.00.00', 0, 'Equipamentos de Informática', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (224, '1.3.2.02.00.00.00', 0, 'Imóveis ', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (225, '1.3.2.03.00.00.00', 0, 'Instalações', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (226, '1.3.2.04.00.00.00', 0, 'Máquinas e Equipamentos', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (227, '1.3.2.05.00.00.00', 0, 'Móveis e Utensílios', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (228, '1.3.2.06.00.00.00', 0, 'Veículos', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (229, '1.3.2.07.00.00.00', 0, '(-) Depreciação Acumulada', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (230, '1.3.3.00.00.00.00', 0, 'Diferido', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (231, '1.3.3.01.00.00.00', 0, 'Despesas Pré-Operacionais', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (232, '1.3.3.02.00.00.00', 0, 'Despesas com Desenvolvimento de Sistemas', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (233, '1.2.2.02.00.00.00', 0, 'Despesas com Desenvolvimento de Novos Produtos ', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (234, '1.3.3.02.00.00.00', 0, '(-) Amortização Acumulada', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (235, '2.0.0.00.00.00.00', 0, 'PASSIVO', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (236, '2.1.0.00.00.00.00', 0, 'CIRCULANTE', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (237, '2.1.1.00.00.00.00', 0, 'Obrigações', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (238, '2.1.1.01.00.00.00', 0, 'Fornecedores', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (239, '2.1.1.02.00.00.00', 0, 'Aluguéis a Pagar', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (240, '2.1.1.03.00.00.00', 0, 'Empréstimos a Pagar', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (241, '2.1.1.04.00.00.00', 0, 'ICMS a Recolher', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (242, '2.1.1.05.00.00.00', 0, 'Imposto de Renda a Pagar', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (243, '2.1.1.06.00.00.00', 0, 'IR Fonte a Recolher', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (244, '2.1.1.07.00.00.00', 0, 'Contribuições Previdenciárias  a Recolher ', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (245, '2.1.1.08.00.00.00', 0, 'FGTS a Recolher', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (246, '2.1.1.09.00.00.00', 0, 'Honorários da Diretoria a Pagar', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (247, '2.1.1.10.00.00.00', 0, 'Salários a Pagar', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (248, '2.1.1.11.00.00.00', 0, 'Dividendos a pagar', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (249, '2.1.1.12.00.00.00', 0, 'Outras Obrigações a Pagar', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (250, '2.2.0.00.00.00.00', 0, 'EXIGÍVEL A LONGO PRAZO', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (251, '2.2.1.00.00.00.00', 0, 'Obrigações', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (252, '2.2.1.01.00.00.00', 0, 'Financiamentos a Pagar', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (253, '2.3.0.00.00.00.00', 0, 'RESULTADO DE EXERCÍCIOS FUTUROS', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (254, '2.3.1.00.00.00.00', 0, 'Resultados Futuros', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (255, '2.3.1.01.00.00.00', 0, 'Receitas de Exercícios Futuros ', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (256, '2.3.1.02.00.00.00', 0, '(-) Custos e Despesas', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (257, '2.4.0.00.00.00.00', 0, 'PATRIMÔNIO LÍQUIDO', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (258, '2.4.1.00.00.00.00', 0, 'Capital', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (259, '2.4.1.01.00.00.00', 0, 'Capital', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (260, '2.4.1.02.00.00.00', 0, '(-) Capital a Realizar', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (261, '2.4.2.00.00.00.00', 0, 'Reservas de Capital', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (262, '2.4.2.01.00.00.00', 0, 'Ágio na Emissão de Ações', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (263, '2.4.3.00.00.00.00', 0, 'Reservas de Reavaliação', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (264, '2.4.3.01.00.00.00', 0, 'Reavaliação do Permanente', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (265, '2.4.4.00.00.00.00', 0, 'Reservas de Lucros', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (266, '2.4.4.01.00.00.00', 0, 'Reserva Legal', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (267, '2.4.5.00.00.00.00', 0, 'Lucros ou Prejuízos Acumulados', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (268, '2.4.5.01.00.00.00', 0, 'Lucros Acumulados', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (269, '2.4.5.02.00.00.00', 0, '(-) Prejuízos Acumulados', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (270, '3.0.0.00.00.00.00', 0, 'DESPESAS  ', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (271, '3.3.0.00.00.00.00', 0, 'DESPESAS OPERACIONAIS', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (272, '3.3.1.00.00.00.00', 0, 'Despesas com Vendas', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (273, '3.3.1.01.00.00.00', 0, 'Comissões sobre Vendas', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (274, '3.3.1.06.00.00.00', 0, 'Fretes e Carretos', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (275, '3.3.1.07.00.00.00', 0, 'Material de Embalagem', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (276, '3.3.1.08.00.00.00', 0, 'Propaganda e Publicidade', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (277, '3.3.1.09.00.00.00', 0, 'Despesas c/ Devedores  Duvidosos', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (278, '3.3.2.00.00.00.00', 0, 'Despesas Administrativas', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (279, '3.3.2.01.00.00.00', 0, 'Aluguel ', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (280, '3.3.2.02.00.00.00', 0, 'Energia Elétrica', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (281, '3.3.2.03.00.00.00', 0, 'Água ', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (282, '3.3.2.04.00.00.00', 0, 'Correios ', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (283, '3.3.2.05.00.00.00', 0, 'Depreciações', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (284, '3.3.2.06.00.00.00', 0, 'Amortizações', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (285, '3.3.2.07.00.00.00', 0, 'Fretes e Carretos', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (286, '3.3.2.08.00.00.00', 0, 'Material de Expediente', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (287, '3.3.2.09.00.00.00', 0, 'Prêmios de Seguro', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (288, '3.3.2.10.00.00.00', 0, 'Comunicações', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (289, '3.3.2.11.00.00.00', 0, 'Impostos e Taxas', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (290, '3.3.2.12.00.00.00', 0, 'Serviços de Terceiros', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (291, '3.3.2.13.00.00.00', 0, 'Multas Fiscais', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (292, '3.3.2.14.00.00.00', 0, 'Salários', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (293, '3.3.2.15.00.00.00', 0, 'Honorários da Diretoria', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (294, '3.3.2.16.00.00.00', 0, 'Décimo Terceiro Salário', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (295, '3.3.2.17.00.00.00', 0, 'Encargos Sociais', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (296, '3.3.2.18.00.00.00', 0, 'Férias ', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (297, '3.3.3.00.00.00.00', 0, 'Despesas Financeiras', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (298, '3.3.3.01.00.00.00', 0, 'Despesas Bancárias', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (299, '3.3.3.02.00.00.00', 0, 'Juros Passivos', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (300, '3.3.3.03.00.00.00', 0, 'Descontos Concedidos', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (301, '3.3.4.00.00.00.00', 0, 'Outras Despesas Operacionais', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (302, '3.3.4.01.00.00.00', 0, 'Prejuízo de Participação em outras Cias ', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (303, '3.3.4.02.00.00.00', 0, 'Despesas Eventuais', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (304, '3.4.0.00.00.00.00', 0, 'DESPESAS NÃO OPERACIONAIS', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (305, '3.4.1.00.00.00.00', 0, 'Perdas  não Operacionais', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (306, '3.4.1.01.00.00.00', 0, 'Perdas na Alienação de Bens', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (307, '4.0.0.00.00.00.00', 0, 'RECEITAS ', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (308, '4.1.0.00.00.00.00', 0, 'RECEITAS OPERACIONAIS', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (309, '4.1.1.00.00.00.00', 0, 'Receitas de Vendas ', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (310, '4.1.1.01.00.00.00', 0, 'Venda de Mercadorias', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (311, '4.1.1.02.00.00.00', 0, '(-) Vendas Anuladas', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (312, '4.1.1.03.00.00.00', 0, '(-) ICMS sobre Vendas', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (313, '4.1.1.04.00.00.00', 0, '(-) PIS sobre Faturamento', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (314, '4.1.2.00.00.00.00', 0, 'Receitas de Serviços prestados', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (315, '4.1.2.01.00.00.00', 0, 'Venda de Serviços', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (316, '4.1.2.04.00.00.00', 0, '(-) ISSQN sobre Faturamento', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (317, '4.1.3.00.00.00.00', 0, 'Receitas Financeiras', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (318, '4.1.3.01.00.00.00', 0, 'Rendimentos de Aplicações Financeiras', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (319, '4.1.3.02.00.00.00', 0, 'Descontos Obtidos', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (320, '4.1.3.03.00.00.00', 0, 'Juros Ativos', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (321, '4.1.4.00.00.00.00', 0, 'Outras Receitas Operacionais', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (322, '4.1.4.01.00.00.00', 0, 'Lucros de Participações em Outras Cias', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (323, '4.1.4.02.00.00.00', 0, 'Reversão de Provisão Para Devedores Duvidosos ', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (324, '4.1.4.03.00.00.00', 0, 'Receitas Eventuais', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (325, '4.2.0.00.00.00.00', 0, 'RECEITAS NÃO OPERACIONAIS', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (326, '4.2.1.00.00.00.00', 0, 'Ganhos não Operacionais', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (327, '4.2.1.01.00.00.00', 0, 'Ganho na Alienação de Bens', 'CREDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (328, '5.0.0.00.00.00.00', 0, 'CONTAS DE APURAÇÃO DE RESULTADOS', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (329, '5.1.0.00.00.00.00', 0, 'APURAÇÃO DE RESULTADO', 'CREDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (330, '5.1.1.00.00.00.00', 0, 'Apuração de Resultado', 'DEVEDORA', 'SINTETICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (331, '5.1.1.01.00.00.00', 0, 'Custo das Mercadorias Vendidas (CMV)', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (332, '5.1.1.02.00.00.00', 0, 'Resultado com Vendas de Mercadorias (RVM)', 'DEVEDORA', 'ANALITICA', 1);
INSERT INTO contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) VALUES (333, '5.1.1.03.00.00.00', 0, 'Apuração do Resultado do Exercício (ARE)', 'DEVEDORA', 'ANALITICA', 1);
