insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (1,  '1.0.0.00.00.00.00', 1, 'ATIVO', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (2,  '1.1.0.00.00.00.00', 2, 'ATIVO CIRCULANTE', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (3,  '1.1.1.00.00.00.00', 3, 'Caixa', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (4,  '1.1.1.01.00.00.00', 4, 'Caixa Geral', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (5,  '1.1.2.00.00.00.00', 3, 'Bancos C/Movimento', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (6,  '1.1.2.01.00.00.00', 4, 'Banco Alfa', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (7,  '1.1.3.00.00.00.00', 3, 'Contas a Receber', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (8,  '1.1.3.01.00.00.00', 4, 'Clientes', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (9,  '1.1.3.02.00.00.00', 4, 'Outras Contas a Receber', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (10, '1.1.3.09.00.00.00', 4, '(-) Duplicatas Descontadas', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (11, '1.1.4.00.00.00.00', 3, 'Estoques', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (12, '1.1.4.01.00.00.00', 4, 'Mercadorias', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (13, '1.1.4.02.00.00.00', 4, 'Produtos Acabados', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (14, '1.1.4.03.00.00.00', 4, 'Insumos', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (15, '1.1.4.04.00.00.00', 4, 'Outros', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (16, '1.2.0.00.00.00.00', 2, 'NãO CIRCULANTE', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (17, '1.2.1.00.00.00.00', 3, 'Contas a Receber', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (18, '1.2.1.01.00.00.00', 4, 'Clientes', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (19, '1.2.1.02.00.00.00', 4, 'Outras Contas', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (20, '1.2.2.00.00.00.00', 3, 'INVESTIMENTOS', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (21, '1.2.2.01.00.00.00', 4, 'Participações Societárias', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (22, '1.2.3.00.00.00.00', 3, 'IMOBILIZADO', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (23, '1.2.3.01.00.00.00', 4, 'Terrenos', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (24, '1.2.3.02.00.00.00', 4, 'Construções e Benfeitorias', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (25, '1.2.3.03.00.00.00', 4, 'Máquinas e Ferramentas', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (26, '1.2.3.04.00.00.00', 4, 'Veículos', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (27, '1.2.3.05.00.00.00', 4, 'Móveis', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (28, '1.2.3.98.00.00.00', 4, '(-) Depreciação Acumulada', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (29, '1.2.3.99.00.00.00', 4, '(-) Amortização Acumulada', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (30, '1.2.4.00.00.00.00', 3, 'INTANGÍVEL', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (31, '1.2.4.01.00.00.00', 4, 'Marcas', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (32, '1.2.4.02.00.00.00', 4, 'Softwares', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (33, '1.2.4.99.00.00.00', 4, '(-) Amortização Acumulada', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (34, '2.0.0.00.00.00.00', 1, 'PASSIVO', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (35, '2.1.0.00.00.00.00', 2, 'CIRCULANTE', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (36, '2.1.1.00.00.00.00', 3, 'Impostos e Contribuições a Recolher', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (37, '2.1.1.01.00.00.00', 4, 'Simples a Recolher', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (38, '2.1.1.02.00.00.00', 4, 'INSS', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (39, '2.1.1.03.00.00.00', 4, 'FGTS', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (40, '2.1.2.00.00.00.00', 3, 'Contas a Pagar', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (41, '2.1.2.01.00.00.00', 4, 'Fornecedores', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (42, '2.1.2.02.00.00.00', 4, 'Outras Contas', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (43, '2.1.3.00.00.00.00', 3, 'Empréstimos Bancários', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (44, '2.1.3.01.00.00.00', 4, 'Banco A - Operações X', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (45, '2.2.0.00.00.00.00', 2, 'NÃO CIRCULANTE', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (46, '2.2.1.00.00.00.00', 3, 'Empréstimos Bancários', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (47, '2.2.1.01.00.00.00', 4, 'Banco A - Operações X', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (48, '2.3.0.00.00.00.00', 2, 'PATRIMôNIO LíQUIDO', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (49, '2.3.1.00.00.00.00', 3, 'Capital Social', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (50, '2.3.2.01.00.00.00', 4, 'Capital Social Subscrito', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (51, '2.3.2.02.00.00.00', 4, 'Capital Social a Realizar', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (52, '2.3.2.00.00.00.00', 3, 'Reservas', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (53, '2.3.2.01.00.00.00', 4, 'Reservas de Capital', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (54, '2.3.3.00.00.00.00', 3, 'Reservas de Lucros', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (55, '2.3.3.01.00.00.00', 4, 'Prejuízos Acumulados', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (56, '2.3.2.02.00.00.00', 4, 'Prejuízos Acumulados de Exercícios Anteriores', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (57, '2.3.3.02.00.00.00', 4, 'Prejuízos do Exercício Atual', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (58, '3.0.0.00.00.00.00', 1, 'CUSTOS E DESPESAS', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (59, '3.1.0.00.00.00.00', 2, 'Custos dos Produtos Vendidos', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (60, '3.1.1.00.00.00.00', 3, 'Custos dos Materiais', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (61, '3.1.1.01.00.00.00', 4, 'Custos dos Materiais Aplicados', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (62, '3.1.2.00.00.00.00', 3, 'Custos da Mão-de-Obra', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (63, '3.1.2.01.00.00.00', 4, 'Salários', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (64, '3.1.2.02.00.00.00', 4, 'Encargos Sociais', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (65, '3.2.0.00.00.00.00', 2, 'Custo das Mercadorias Vendidas', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (66, '3.2.1.00.00.00.00', 3, 'Custo das Mercadorias', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (67, '3.2.1.01.00.00.00', 4, 'Custo das Mercadorias Vendidas', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (68, '3.3.0.00.00.00.00', 2, 'Custo dos Serviços Prestados', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (69, '3.3.1.00.00.00.00', 3, 'Custo dos Serviços', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (70, '3.3.1.01.00.00.00', 4, 'Materiais Aplicados', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (71, '3.3.1.02.00.00.00', 4, 'Mão-de-Obra', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (72, '3.3.1.03.00.00.00', 4, 'Encargos Sociais', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (73, '3.4.0.00.00.00.00', 2, 'Despesas Operacionais', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (74, '3.4.1.00.00.00.00', 3, 'Despesas Gerais', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (75, '3.4.1.01.00.00.00', 4, 'Mão-de-Obra', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (76, '3.4.1.02.00.00.00', 4, 'Encargos Sociais', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (77, '3.4.1.03.00.00.00', 4, 'Aluguéis', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (78, '3.5.0.00.00.00.00', 2, 'Perdas de Capital', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (79, '3.5.1.00.00.00.00', 3, 'Baixa de Bens do Ativo Não Circulante', 'DEVEDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (80, '3.5.1.01.00.00.00', 4, 'Custos de Alienação de Investimentos', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (81, '3.5.1.02.00.00.00', 4, 'Custos de Alienação do Imobilizado', 'DEVEDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (82, '4.0.0.00.00.00.00', 1, 'RECEITAS', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (83, '4.1.0.00.00.00.00', 2, 'Receita Líquida', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (84, '4.1.1.00.00.00.00', 3, 'Receita Bruta de Vendas', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (85, '4.1.1.01.00.00.00', 4, 'De Mercadorias', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (86, '4.1.1.02.00.00.00', 4, 'De Produtos', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (87, '4.1.1.03.00.00.00', 4, 'De Serviços Prestados', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (88, '4.1.2.00.00.00.00', 3, 'Deduções da Receita Bruta', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (89, '4.1.2.01.00.00.00', 4, 'Devoluções', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (90, '4.1.2.02.00.00.00', 4, 'Serviços Cancelados', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (91, '4.2.0.00.00.00.00', 2, 'Outras Receitas Operacionais', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (92, '4.2.1.00.00.00.00', 3, 'Vendas de Ativos Não Circulantes', 'CREDORA', 'SINTETICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (93, '4.2.1.01.00.00.00', 4, 'Receitas de Alienação de Investimentos', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (94, '4.2.1.02.00.00.00', 4, 'Receitas de Alienação do Imobilizado', 'CREDORA', 'ANALITICA', 1);
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, id_plano_contas) values (95, '1.1.2.02.00.00.00', 4, 'Banco Bradesco', 'DEVEDORA', 'ANALITICA', 1);
-- contas com outros proprietários                                                                      
insert into contas(id_conta, estrutura, nivel, nome, conta_origem, conta_tipo, ID_EMPRESA)      values (96, '1.1.2.04.00.00.00', 4, 'Conta da empresa 1', 'DEVEDORA', 'ANALITICA', 1);