insert into EXERCICIO (ID_EXERCICIO, ID_EMPRESA, ID_PLANO_CONTAS, ANO, FECHADO)values (1, 1, 1, 2017, false);
insert into EXERCICIO (ID_EXERCICIO, ID_EMPRESA, ID_PLANO_CONTAS, ANO, FECHADO)values (2, 1, 1, 2016, false);
insert into EXERCICIO (ID_EXERCICIO, ID_EMPRESA, ID_PLANO_CONTAS, ANO, FECHADO)values (3, 1, 1, 2015, false);
insert into EXERCICIO (ID_EXERCICIO, ID_EMPRESA, ID_PLANO_CONTAS, ANO, FECHADO)values (4, 2, 1, 2016, false);
insert into EXERCICIO (ID_EXERCICIO, ID_EMPRESA, ID_PLANO_CONTAS, ANO, FECHADO)values (5, 2, 1, 2017, false);