INSERT INTO LANCAMENTO_PADRAO (ID_LANCAMENTO_PADRAO, NOME, DEBITO, CREDITO, ID_HISTORICO_PADRAO)VALUES(1,'Venda de serviços a vista',203,315,1)
INSERT INTO LANCAMENTO_PADRAO (ID_LANCAMENTO_PADRAO, NOME, DEBITO, CREDITO, ID_HISTORICO_PADRAO)VALUES(2,'Venda de serviços a prazo',206,315,1)
INSERT INTO LANCAMENTO_PADRAO (ID_LANCAMENTO_PADRAO, NOME, DEBITO, CREDITO, ID_HISTORICO_PADRAO)VALUES(3,'Despesa com aluguel a vista',279,203,5)
